import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { AlertProvider } from './components/ui/Alert'
import { ThemeProvider } from './contexts/ThemeContext'
import Header from './components/layout/Header'
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Nodalyn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ThemeProvider>
          <AlertProvider>
            <Header />
            {children}
          </AlertProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
